### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by Jzarecta** [AugurProject/augur-core#85]
I get some errors might be related with python2 / 3 compatibility.
```python
>>> import serpent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/serpent.py", line 225
    print json.dumps(o)
```
python3 is print() not print.
```python
    form serpent_setup import *
                     ^
SyntaxError: invalid syntax
```

**Comment by Jzarecta** [comment]
oops sorry wrong repo :p
